config/routes.rb
Jetter::Application.routes.draw do
  resources :users

  resources :jets

  get "home/index"

    root :to => 'home#index'

end

app/models/jet.rb
class Jet < ActiveRecord::Base

  attr_accessible :content, :userid
  validates :content, :presence => true,
                      :length => { :maximum => 140 }

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
  validates :name, :presence => true,
                   :uniqueness => true
  validates :password, :presence => true,
                       :length => { :minimum => 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController
  # GET /jets
  # GET /jets.json
  def index
    @jets = Jet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jets }
    end
  end

  # GET /jets/1
  # GET /jets/1.json
  def show
    @jet = Jet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jet }
    end
  end

  # GET /jets/new
  # GET /jets/new.json
  def new
    @jet = Jet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jet }
    end
  end

  # GET /jets/1/edit
  def edit
    @jet = Jet.find(params[:id])
  end

  # POST /jets
  # POST /jets.json
  def create
    @jet = Jet.new(params[:jet])

    respond_to do |format|
      if @jet.save
        format.html { redirect_to @jet, notice: 'Jet was successfully created.' }
        format.json { render json: @jet, status: :created, location: @jet }
      else
        format.html { render action: "new" }
        format.json { render json: @jet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jets/1
  # PUT /jets/1.json
  def update
    @jet = Jet.find(params[:id])

    respond_to do |format|
      if @jet.update_attributes(params[:jet])
        format.html { redirect_to @jet, notice: 'Jet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jets/1
  # DELETE /jets/1.json
  def destroy
    @jet = Jet.find(params[:id])
    @jet.destroy

    respond_to do |format|
      format.html { redirect_to jets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to jets_path }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jets_helper.rb
module JetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<html>
	<head>
		<title>
			Jetter
		</title>
		<style>
			body {
				padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
			}
		</style>
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="nav-collapse">
					<ul class="nav">
						<li><%= link_to image_tag("logo.png", :border => 0), {}, {}%></li>
					</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<h1>Let your world fly on jet!</h1>
			<h3>Please login to take off</h3>
			<%= link_to "Sign in/Sign up", "/users/new" %>
		</div>
	</body>
</html>

app/views/jets/_form.html.erb
<html>
  <head>
 <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
		
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
	<div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to image_tag("logo.png", :border => 0), {}, {}%></li>
		<li><a href="../">Logout</a></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
<%= form_for(@jet) do |f| %>
  <% if @jet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jet.errors.count, "error") %> prohibited this jet from being saved:</h2>

      <ul>
      <% @jet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/jets/edit.html.erb
<h1>Editing jet</h1>

<%= render 'form' %>

<%= link_to 'Show', @jet %> |
<%= link_to 'Back', jets_path %>

app/views/jets/index.html.erb
<html>
<head>
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to image_tag("logo.png", :border => 0), {}, {}%></li>
		<li><a href="../">Logout</a></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="container">
<h1>Your timeline!</h1>

<br />
<%= link_to 'Drive new jet', new_jet_path %><br/><br/>
<%
def getUserName(id)
  user = User.find_by_id(id)
  return user.name
end
%>
<% @jets.each do |jet| %>
<div class="hero-unit">
  Jet driven by <b><%= getUserName(jet.userid) %></b> <%= jet.created_at.strftime(" on %B %d, %Y at %I:%M %p") %><br/>
    <%= jet.content %><br/><br/>
    
    <%= link_to 'Delete jet', jet, confirm: 'Are you sure?', method: :delete %></div>
<% end %>


<br />


</body>
</html>

app/views/jets/new.html.erb
<h1>New jet</h1>

<%= render 'form' %>

<%= link_to 'Back', jets_path %>

app/views/jets/show.html.erb
<html>
<head>
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to image_tag("logo.png", :border => 0), {}, {}%></li>
		<li><a href="../">Logout</a></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @jet.userid %>
</p>

<p>
  <b>Content:</b>
  <%= @jet.content %>
</p>


<%= link_to 'Edit', edit_jet_path(@jet) %> |
<%= link_to 'Back', jets_path %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jetter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
		<style>
			body {
				padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
			}
		</style>
</head>
<body>

<span style="position:absolute;left:210px"><%= yield %></span>

</body>
</html>


app/views/users/_form.html.erb
<html>
  <head>
 <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
		
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
	<div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to image_tag("logo.png", :border => 0), {}, {}%></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', "/" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>